# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('current_user_count', models.IntegerField(default=0)),
                ('max_current_user_count', models.IntegerField(default=15)),
                ('multi_processing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_nr', models.IntegerField()),
                ('stimuli', models.TextField()),
                ('answer_type', models.CharField(choices=[('acr', 'ACR'), ('text', 'Text'), ('choice', 'Multiple Choice')], max_length=10)),
            ],
            options={
                'ordering': ['block_nr'],
            },
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('img', 'Image'), ('aud', 'Audio'), ('vid', 'Video'), ('txt', 'Text')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_nr', models.IntegerField()),
                ('instruction', models.CharField(blank=True, default='', max_length=255)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Campaign')),
            ],
            options={
                'ordering': ['task_nr'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_task', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateField(blank=True, default=0)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Campaign')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='rating_block',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Task'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stimuli',
            field=models.ManyToManyField(to='crowd.Stimulus'),
        ),
        migrations.AddField(
            model_name='answerchoices',
            name='rating_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Rating_block'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.Rating_block'),
        ),
        migrations.AddField(
            model_name='answer',
            name='worker_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.WorkerProgress'),
        ),
    ]
