# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0004_auto_20170807_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trap_answer',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
